seed: 42

data:
  csv_path: "train_processed.csv"
  images_root: datasets/ml_ozon_сounterfeit_train_images
  #img_size: 224
  num_workers: 4

model:
  clip_model_name: "ViT-B-32"
  openclip_pretrained: "laion2b_s34b_b79k"     # веса для open-clip
  image_emb_dim: 512
  text_model: "DeepPavlov/rubert-base-cased"
  text_max_len: 128

train:
  batch_size: 64
  #epochs: 10
  #lr: 0.0001
  #weight_decay: 0.0001
  device: "cpu"

catboost:
  iterations: 5000
  learning_rate: 0.05
  depth: 6
  l2_leaf_reg: 3.0
  early_stopping_rounds: 200
  eval_metric: "AUC"
  loss_function: "Logloss"
  use_gpu: true
  threshold: 0.5

wandb: #weight and biases - для трекинга экспериментов
  use: true
  project: "e-cup-2025"
  entity: "your_wandb_account"